name: Java CI for Feature Branches (Minecraft 1.8 Plugin)

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn test

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: target/*.jar